name: Cypress CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        options:
          - dev
          - stg
          - prod
        required: true

env:
  DEFAULT_BRANCH: test

permissions:
    id-token: write
    contents: read

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Set environment 
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" > $ENV

      - name: Build the cypress docker image
        working-directory: ./test_cypress
        run: docker build . --file Dockerfile --tag cypress-ci
      
      - name: Run
        working-directory: ./test_cypress
        run: docker run cypress-ci
